vfs: prevent hiding of close() overloads
The change prevents the following build errors on riscv.

In file included from /data/depot/checker/api/vfs/2025-05-18/include/vfs/readonly_value_file_system.h:19,
                 from /data/depot/checker/src/vfs_legacy_oss/2025-05-18/src/lib/vfs/legacy_oss/vfs_oss.cc:22:
/data/depot/checker/api/vfs/2025-05-18/include/vfs/readonly_value_file_system.h: In instantiation of ‘class Vfs::Readonly_value_file_system<unsigned int>’:
/data/depot/checker/src/vfs_legacy_oss/2025-05-18/src/lib/vfs/legacy_oss/vfs_oss.cc:152:26:   required from here
  152 |                                 _channels_fs         .value(channels);
      |                                                      ^
/data/depot/checker/api/vfs/2025-05-18/include/vfs/single_file_system.h:229:22: error: ‘virtual void Vfs::Single_file_system::close(Vfs::Vfs_handle*)’ was hidden [-Werror=overloaded-virtual=]
  229 |                 void close(Vfs_handle *handle) override
      |                      ^~~~~
/data/depot/checker/api/vfs/2025-05-18/include/vfs/readonly_value_file_system.h:170:22: note:   by ‘void Vfs::Readonly_value_file_system< <template-parameter-1-1>, BUF_SIZE>::close(Vfs::Vfs_watch_handle*) [with T = unsigned int; unsigned int BUF_SIZE = 128]’
  170 |                 void close(Vfs_watch_handle *handle) override
      |                      ^~~~~

https://stackoverflow.com/questions/9995421/gcc-woverloaded-virtual-warnings
suggests to address this by an explicit using statement.

Issue #5540